import type { Product } from '@/types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Meditación Guiada 30 min',
    price: 80000,
    description: 'Sesión grabada de meditación guiada para calmar la mente y reducir el estrés.',
    imageUrl: '',
    category: 'Mundo Mente',
    unitsSold: 34,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Diario de Gratitud',
    price: 45000,
    description: 'Diario estructurado para cultivar la gratitud y la consciencia diaria.',
    imageUrl: '',
    category: 'Mundo Alma',
    unitsSold: 18,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Clase de Yoga Online',
    price: 60000,
    description: 'Acceso a una clase de yoga completa para todos los niveles.',
    imageUrl: '',
    category: 'Mundo Cuerpo',
    unitsSold: 52,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Kit de Cristales de Cuarzo',
    price: 120000,
    description: 'Set de 4 cristales de cuarzo rosa, amatista, citrino y cuarzo blanco.',
    imageUrl: '',
    category: 'Mundo Energía',
    unitsSold: 9,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: 'Aceite Esencial de Lavanda',
    price: 55000,
    description: 'Aceite esencial 100% puro de lavanda para aromaterapia y bienestar.',
    imageUrl: '',
    category: 'Mundo Naturaleza',
    unitsSold: 41,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: 'Sesión de Coaching 1:1',
    price: 250000,
    description: 'Sesión individual de coaching holístico de 60 minutos por videollamada.',
    imageUrl: '',
    category: 'Mundo Mente',
    unitsSold: 7,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: 'Incienso Natural Palo Santo',
    price: 35000,
    description: 'Varitas de palo santo 100% natural para limpiar y armonizar espacios.',
    imageUrl: '',
    category: 'Mundo Naturaleza',
    unitsSold: 63,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    price: 180000,
    description: 'Mat de yoga antideslizante de 6mm, ecológico y libre de PVC.',
    imageUrl: '',
    category: 'Mundo Cuerpo',
    unitsSold: 15,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: 'Ritual de Luna Llena',
    price: 90000,
    description: 'Guía completa y materiales para realizar tu ritual de luna llena en casa.',
    imageUrl: '',
    category: 'Mundo Alma',
    unitsSold: 22,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: 'Collar de Turmalina Negra',
    price: 95000,
    description: 'Collar de protección energética con piedra de turmalina negra natural.',
    imageUrl: '',
    category: 'Mundo Energía',
    unitsSold: 11,
    status: 'active',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
